"""Market monitor for signal generation"""

import logging
from typing import List, Optional, Dict, Tuple
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
import numpy as np

logger = logging.getLogger(__name__)


class SignalType(Enum):
    """Signal types for trading decisions"""
    BUY = "BUY"
    SELL = "SELL"
    NEUTRAL = "NEUTRAL"


@dataclass
class Signal:
    """Trading signal generated by market monitor"""
    signal_id: str
    contract_id: str
    title: str
    signal_type: SignalType
    confidence: float  # 0.0 to 1.0
    price: float
    quantity: int
    reason: str
    created_at: datetime = field(default_factory=datetime.now)


@dataclass
class MarketData:
    """Historical market data for analysis"""
    contract_id: str
    timestamp: datetime
    price: float
    bid: float
    ask: float
    volume: float


class MarketMonitor:
    """Monitors market conditions and generates trading signals"""

    def __init__(self, lookback_period: int = 20, vol_threshold: float = 0.15):
        """
        Initialize market monitor

        Args:
            lookback_period: Number of periods for momentum calculation
            vol_threshold: Volatility threshold for momentum signals
        """
        self.lookback_period = lookback_period
        self.vol_threshold = vol_threshold
        self.market_history: Dict[str, List[MarketData]] = {}
        self.signals: List[Signal] = []

    def add_market_data(self, contract_id: str, price: float, bid: float, ask: float, volume: float):
        """
        Add market data point to history

        Args:
            contract_id: Contract ID
            price: Current price
            bid: Current bid price
            ask: Current ask price
            volume: Volume in last period
        """
        if contract_id not in self.market_history:
            self.market_history[contract_id] = []

        data = MarketData(
            contract_id=contract_id,
            timestamp=datetime.now(),
            price=price,
            bid=bid,
            ask=ask,
            volume=volume
        )

        self.market_history[contract_id].append(data)

        # Keep only recent history
        if len(self.market_history[contract_id]) > self.lookback_period * 2:
            self.market_history[contract_id] = self.market_history[contract_id][-self.lookback_period * 2:]

    def detect_momentum(self, contract_id: str) -> Tuple[Optional[SignalType], float]:
        """
        Detect vol-scaled momentum signal

        Args:
            contract_id: Contract to analyze

        Returns:
            Tuple of (signal_type, confidence)
        """
        if contract_id not in self.market_history:
            return None, 0.0

        history = self.market_history[contract_id]
        if len(history) < self.lookback_period:
            return None, 0.0

        # Get recent prices
        prices = np.array([data.price for data in history[-self.lookback_period:]])

        # Calculate returns
        returns = np.diff(prices) / prices[:-1]

        # Calculate volatility (standard deviation of returns)
        volatility = np.std(returns)

        # Calculate momentum (mean of recent returns)
        momentum = np.mean(returns)

        # Vol-scaled momentum: momentum / volatility
        if volatility > 0:
            vol_scaled_momentum = momentum / volatility
        else:
            vol_scaled_momentum = 0

        # Generate signal based on vol-scaled momentum
        if vol_scaled_momentum > self.vol_threshold:
            confidence = min(0.95, 0.5 + vol_scaled_momentum)
            return SignalType.BUY, confidence

        elif vol_scaled_momentum < -self.vol_threshold:
            confidence = min(0.95, 0.5 + abs(vol_scaled_momentum))
            return SignalType.SELL, confidence

        return SignalType.NEUTRAL, 0.0

    def detect_structural_sub_20_no(self, contract_id: str, market_title: str) -> Tuple[Optional[SignalType], float]:
        """
        Detect structural sub-20¢ NO opportunity

        Identifies markets where NO (opposite) is trading below $0.20,
        suggesting potential value opportunity

        Args:
            contract_id: Contract ID (e.g., "market_id-no")
            market_title: Market title for context

        Returns:
            Tuple of (signal_type, confidence)
        """
        if contract_id not in self.market_history:
            return None, 0.0

        history = self.market_history[contract_id]
        if len(history) == 0:
            return None, 0.0

        latest_price = history[-1].price

        # Sub-20¢ opportunity on NO
        if latest_price < 0.20:
            # Calculate how much below 20¢
            discount = (0.20 - latest_price) / 0.20
            confidence = min(0.90, 0.60 + discount)

            logger.info(f"📍 Sub-20¢ NO detected: {market_title} @ ${latest_price:.2f}")
            return SignalType.BUY, confidence

        return SignalType.NEUTRAL, 0.0

    def detect_bundle_arbitrage(
        self,
        related_contracts: Dict[str, float]
    ) -> Tuple[Optional[SignalType], float]:
        """
        Detect bundle arbitrage opportunity

        When multiple related contracts can be combined into a covered position,
        look for pricing inefficiencies

        Args:
            related_contracts: Dict of {contract_id: price}

        Returns:
            Tuple of (signal_type, confidence)
        """
        if len(related_contracts) < 2:
            return None, 0.0

        prices = list(related_contracts.values())

        # Bundle should sum to ~1.0 for complementary contracts
        bundle_sum = sum(prices)

        # Arbitrage opportunity if bundle is significantly mispriced
        if bundle_sum < 0.95:  # Bundle trading below intrinsic value
            discount = (1.0 - bundle_sum)
            confidence = min(0.85, 0.65 + discount * 10)

            logger.info(f"🎯 Bundle arbitrage detected: sum={bundle_sum:.2f}")
            return SignalType.BUY, confidence

        elif bundle_sum > 1.05:  # Bundle trading above intrinsic value
            overvaluation = bundle_sum - 1.0
            confidence = min(0.85, 0.65 + overvaluation * 10)

            logger.info(f"🎯 Bundle overvaluation detected: sum={bundle_sum:.2f}")
            return SignalType.SELL, confidence

        return SignalType.NEUTRAL, 0.0

    def generate_signal(
        self,
        contract_id: str,
        title: str,
        market_price: float,
        quantity: int = 10
    ) -> Optional[Signal]:
        """
        Generate trading signal for contract

        Args:
            contract_id: Kalshi contract ID
            title: Market title
            market_price: Current market price
            quantity: Suggested quantity to trade

        Returns:
            Signal object or None if no actionable signal
        """
        # Run multiple signal detectors
        momentum_signal, momentum_conf = self.detect_momentum(contract_id)
        sub20_signal, sub20_conf = self.detect_structural_sub_20_no(contract_id, title)

        # Combine signals (prefer highest confidence)
        best_signal = None
        best_confidence = 0.0
        reason = ""

        if momentum_conf > best_confidence:
            best_signal = momentum_signal
            best_confidence = momentum_conf
            reason = f"Vol-scaled momentum ({best_confidence:.0%})"

        if sub20_conf > best_confidence:
            best_signal = sub20_signal
            best_confidence = sub20_conf
            reason = f"Sub-20¢ NO opportunity ({best_confidence:.0%})"

        # Only generate signal if confidence exceeds threshold
        if best_signal and best_signal != SignalType.NEUTRAL and best_confidence >= 0.60:
            signal = Signal(
                signal_id=f"SIG-{datetime.now().strftime('%Y%m%d%H%M%S')}-{contract_id}",
                contract_id=contract_id,
                title=title,
                signal_type=best_signal,
                confidence=best_confidence,
                price=market_price,
                quantity=quantity,
                reason=reason
            )

            self.signals.append(signal)
            logger.info(
                f"🔔 Signal generated: {signal.signal_type.value} {title} "
                f"@ ${market_price:.2f} ({reason})"
            )

            return signal

        return None

    def get_recent_signals(self, limit: int = 10) -> List[Signal]:
        """
        Get recent signals

        Args:
            limit: Max number of signals to return

        Returns:
            List of recent signals
        """
        return self.signals[-limit:]

    def clear_history(self, contract_id: Optional[str] = None):
        """
        Clear market history

        Args:
            contract_id: If specified, only clear this contract's history
        """
        if contract_id:
            self.market_history.pop(contract_id, None)
        else:
            self.market_history.clear()
